### ISSUE TITLE
Designer url, Manufacturer and Manufacturer urls missing

### ISSUE THREAD

**Issue by m4rc1e** [agoodfeelingco/bakbak#1]
Would it be possible get the fields listed in the title?

Is A Good Feeling the manufacturer?

cc @davelab6

**Comment by sanketavlani** [comment]
Yes please, and the URL is www.agoodfeeling.co

Designers: Sanchit Sawaria & Saumya Kishore

**Comment by davelab6** [comment]
@m4rc1e the designer URL is www.struckby.co

**Comment by m4rc1e** [comment]
@davelab6 info was added in #2 

![screen shot 2017-08-03 at 10 24 40](https://user-images.githubusercontent.com/7525512/28915124-04692044-7836-11e7-8a5a-fcc61c291678.png)

**Comment by davelab6** [comment]
please close this issue
